# Generated by Django 6.0.3 on 2026-04-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_control', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('primer_ap', models.CharField(max_length=40)),
                ('segundo_ap', models.CharField(max_length=40)),
                ('fecha_nac', models.DateField()),
                ('semestre', models.SmallIntegerField()),
                ('carrera', models.CharField(max_length=100)),
            ],
        ),
    ]
